### ISSUE TITLE
DPL-232 - We want to track the progress of a plate through from arrival with Sample Management to data archived

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#169]
**Description**
We want to track the progress of a plate through from arrival with Sample Management to data archived

**Who the primary contacts are for this work**
Liz / Emma / Steve

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by stevieing** [comment]
Meeting arranged for 20/01

**Comment by stevieing** [comment]
![Lean_time_stamps](https://user-images.githubusercontent.com/519327/150508579-c9191271-da29-4ba8-b49a-38881707a6d3.jpg)

**Comment by stevieing** [comment]
Todo:

- [ ] identify if an event exists for each time stamp.
- [ ] if an event does not exist identify where and how a new event should be added
- [ ] produce a diagram of the event timeline
- [ ] create stories to add any new events
- [ ] identify any areas of complexity or unknowns

**Comment by stevieing** [comment]
Quick discussion (01/02)

The following events exist:
- library start
- library complete
- sequencing start
- sequencing complete

The following data is not managed or held by PSD so you would need to talk to Data QC or NPG as to how this is reported:
Review QC / Auto QC / Investigation QC
Data available to client

Sample Management:
- Could we use Labwhere or Asset Audits. Speak to Danni.

**Comment by stevieing** [comment]
Library start and library complete now mostly get triggered by Limber, I’ll see if I can track down exactl where. I think they are at the plate level, but samples and requests are all linked as subjects.
3:12
Sequencing start gets triggered when the batch is started in SS https://github.com/sanger/sequencescape/blob/01815b18752803118beaf7a8a833764967f380e3/app/models/sequencing_pipeline.rb#L56
sequencing_pipeline.rb
    BroadcastEvent::SequencingStart.create!(seed: batch, user: user, properties: {}, created_at: DateTime.now)
<https://github.com/sanger/sequencescape|sanger/sequencescape>sanger/sequencescape | Added by GitHub
3:13
Sequencing complete gets created at the lane level when we get the pass event back from NPG: https://github.com/sanger/sequencescape/blob/a7c43e591668745dd1283ce3fecf2343781a39e4/app/controllers/npg_actions/assets_controller.rb#L59
assets_controller.rb
    BroadcastEvent::SequencingComplete.create!(seed: @asset, properties: { result: state_str })
<https://github.com/sanger/sequencescape|sanger/sequencescape>sanger/sequencescape | Added by GitHub
3:15
Ahh, library start is part of the plate state-change action: https://github.com/sanger/sequencescape/blob/b03341a3afc4c0f57175183ddcfa660138bf51ea/app/models/state_changer/standard_plate.rb#L47
So it will be triggered once per order on the plate, when the first plate in the pipeline is started. (Usually a robot transfer out of the initial plate)
3:17
It looks like LibraryComplete is currently hooked into passing the MX tube, which doesn’t feel entirely consistent, and would be better off hooked to charge and pass libraries. But poking into that one a little more:
https://github.com/sanger/sequencescape/blob/765fd38b79385a85e82927e7e914b3329d5b67f6/app/models/state_changer/mx_tube.rb#L17
mx_tube.rb
        BroadcastEvent::LibraryComplete.create!(seed: labware, user: user, properties: { order_id: order_id })
<https://github.com/sanger/sequencescape|sanger/sequencescape>sanger/sequencescape | Added by GitHub
3:19
There is also the ability to trigger a ‘library_event’ with a custom type via the API, but we don’t seem to do that any-more.

**Comment by ElizabethEasthope** [comment]
> 
> It looks like LibraryComplete is currently hooked into passing the MX tube, which doesn’t feel entirely consistent, and would be better off hooked to charge and pass libraries. But poking into that one a little more: https://github.com/sanger/sequencescape/blob/765fd38b79385a85e82927e7e914b3329d5b67f6/app/models/state_changer/mx_tube.rb#L17 mx_tube.rb BroadcastEvent::LibraryComplete.create!(seed: labware, user: user, properties: { order_id: order_id }) [https://github.com/sanger/sequencescape|sanger/sequencescape](https://github.com/sanger/sequencescape%7Csanger/sequencescape)sanger/sequencescape
> 
I think Library Complete would be best from the Charge and Passed as some lines don't always make an MX tube within a timely manner.
Thanks

**Comment by stevieing** [comment]
Still to do:

- [ ] Find out about the sample management events
- [ ] Create a story to move the library complete events to charge and pass libraries

**Comment by ElizabethEasthope** [comment]
Hi Stephen,
I was wondering how it going?  If you were able to give me an update that would be great.  
Thanks Liz

**Comment by stevieing** [comment]
Hi Liz

Unfortunately it got to a point where my list of things to do was overflowing so I had to put it on hold.

Thankfully I am clearing the backlog so I will get back to it this week. There is a more general discussion around events and plate tracking so it will definitely start to progress.

Regards

Steve.

On 8 Mar 2022, at 09:38, ElizabethEasthope ***@***.******@***.***>> wrote:



Hi Stephen,
I was wondering how it going? If you were able to give me an update that would be great.
Thanks Liz

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sanger_General-2DBacklog-2DItems_issues_169-23issuecomment-2D1061584222&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PioAYl_Zz9lnGwJRms8MsEB0E-grNRW-ut-_gAGl70g&m=zJKVHB3kxJ4XSrs0H_MPhpnv8B-DgwOeL3bA_KOpwHucM1ckersbVG4AGJCtUk9G&s=9KJjw7PLFjfy_y-pnSnONUQS-dUdE_rx5pn5okVRy0k&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAD6ZH2KNUXKEGZBW53DNYTU64NZVANCNFSM5L3GK5MA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PioAYl_Zz9lnGwJRms8MsEB0E-grNRW-ut-_gAGl70g&m=zJKVHB3kxJ4XSrs0H_MPhpnv8B-DgwOeL3bA_KOpwHucM1ckersbVG4AGJCtUk9G&s=lu6TTP5m9WGrYur6991hz-dIpWx_9esGSsd3bMyp3tw&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PioAYl_Zz9lnGwJRms8MsEB0E-grNRW-ut-_gAGl70g&m=zJKVHB3kxJ4XSrs0H_MPhpnv8B-DgwOeL3bA_KOpwHucM1ckersbVG4AGJCtUk9G&s=ZGCoLTgOJL2bat31V0qxWtlnyMUdJZwHbeSL8F-cOTc&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PioAYl_Zz9lnGwJRms8MsEB0E-grNRW-ut-_gAGl70g&m=zJKVHB3kxJ4XSrs0H_MPhpnv8B-DgwOeL3bA_KOpwHucM1ckersbVG4AGJCtUk9G&s=2zZlcOEgy9km4uX2f2M0LACMXOQVbLn8CPA6TT3ZpYQ&e=>.
You are receiving this because you were assigned.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by ElizabethEasthope** [comment]
Hi Steve,

Thank you for the update.
I’m aware of a KanBan system being looked at and I’ve been asked to be involved with that as well. I thought they probably over lapped.

Thanks
Liz


Elizabeth Easthope
Team Lead for RNA
DNA Pipelines
Wellcome Sanger Institute
Wellcome Genome Campus
Hinxton
CB10 1DR
United Kingdom

Tel: +44 (0) 1223 494979

[logo]

**Comment by stevieing** [comment]
Definitely overlap. We would need to sort out the events to make it work.

On 8 Mar 2022, at 10:58, ElizabethEasthope ***@***.******@***.***>> wrote:


Hi Steve,

Thank you for the update.
I’m aware of a KanBan system being looked at and I’ve been asked to be involved with that as well. I thought they probably over lapped.

Thanks
Liz


Elizabeth Easthope
Team Lead for RNA
DNA Pipelines
Wellcome Sanger Institute
Wellcome Genome Campus
Hinxton
CB10 1DR
United Kingdom

Tel: +44 (0) 1223 494979

[logo]

**Comment by KatyTaylor** [comment]
**Update:**

I'm trying to take an iterative approach with this story:
- first show the customer what kind of reports we can produce using the existing data we have
- get feedback
- decide on most useful next increment (probably adding new events, to track more of the process)

I emailed Liz on Tues 29th March with these reports - https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=137076202 - I've placed this story on hold until she's back and can give feedback on them.

**Comment by KatyTaylor** [comment]
Met with Liz today - update below:

**Actions:**
- Katy - add 'submission name' to the queries - this will be the final tweak for this story (DPL-232)
- Liz - MySQL Workbench limits queries by default to 30 seconds - this may need to be extended
- Katy - check whether there's a replica database Liz could use for queries to avoid spamming prod
- Katy - write up story to include in Plate Tracking OKR - change library_complete to 'charge and pass', and rename multiplexed library tube passing event to 'pool_released'

**Extending benefit to other teams:**
- Liz is working on this project (which came out of the Lean training) together with Liz C, James M, James W, Danni, and is herself representing all of the high-throughput team leads - so our 'key result' to extend this benefit to other teams within DNAP is already well on its way.

**What's next?**
- Liz is happy to use these queries for a few months to test them out
- The likely next step would be to drill down with further time points, probably between the first (LabWhere) and second (library_start) events

**Extra notes:**
- Liz is at the stage now where she can run the queries from this page - https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=137076202 - using MySQL Workbench (currently against the production DB) and produce useful reports and analysis from them.
- The queries are producing some rows where the timestamps are out of order - for instance, a library_complete before a library_start, or a sequencing_complete before a sequencing_start - this could be for 2 reasons:
   - In some queries, we are using the first event of each type - there may be multiple for the same stock plate as it could have been processed through the lab more than once. The timestamps in the lab could be from different runs through the lab, hence being out of order - the earlier timestamp could be out of the specified time window, or it could be a bug if it wasn't fired from the LIMS.
   - We know from experience that people don't always click buttons in the LIMS at the exact time that the physical event happens - if we find this is the case, then we can try to make UX improvements to the software, or change the lab process. Liz now has access to information about what exactly triggers the events in the LIMS (table on same Confluence page linked earlier) - so can assess the lab process.
- We looked at the other information available in the events we were using (again in table on Conf page). Adding submission names would be useful as it gives extra context to the rows in the report, allowing some investigation e.g. if a particular customer's plates always take ages in Sample Management, or if there are timestamps out of order, showing that they are from different submissions. We talked about the possibility of adding extra information into the events, e.g. Product or something to represent the pipeline.

**Comment by KatyTaylor** [comment]
Liz has confirmed the new queries that include the submission name are working for her, so I am closing this issue as done.
