### ISSUE TITLE
DPL-392 Track batches of cherrypicking controls 

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/General-Backlog-Items#190]
*** The Heron team would like to print out one barcode label for a batch, and stick it somewhere near the robots, and scan that in order to record the batch. This will need to be weighed up against the approach we were imagining, where the barcode of the control plates represents the batch.***

**User story**
As a member of the Heron team, I would like control batches to be tracked in the LIMS. This will benefit us because:

- Less work for lab team - can stop recording control batch number in paperwork & Trello
- Better data integrity due to less manual recording of information
- Can investigate relationships between control batches and destination plates (see acceptance criteria) more quickly than currently

**Who are the primary contacts for this story**
Barbora, Katy

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I can generate and print barcodes for control batches (any specific requirements here?)
- [ ] Given a destination plate (LTHR Cherrypick / HT- barcode), I can see the batch number of its control samples
- [ ] Given a control batch number, I can find all the destination plates (LTHR Cherrypick / HT- barcode) it was used on
- [ ] Existing control-related functionality continues to work:
    - Beckman / Biosero code scans control plate and transfers controls to destination plate
    - Heron endpoint creates destination plate, with control samples which have control field set, and supplier name set to `controlplatebarcode_wellposition`
    - Which wells contain controls is visible in SS & Limber
    - Controls are tracked in Beckman / Biosero cherrypicking events

**Additional context**
Current situation:
- No batch tracking in LIMS - the same plate barcode is used over and over again (typed into Lighthouse UI in order to print label)
- A batch number is written in the paperwork (Cherrypicking page, ‘Control batch’), and recorded in Trello

For generating the barcodes:
Could use Mixtio 'out of the box'. Would need to have a conversation with CGaP to check it won't disrupt their work, and check that using barcodes prefixed with `CGAP-` is OK. 
Otherwise, we could come up with a solution using Baracoda to generate the barcodes. Will also need to check that the Beckman / Biosero code doesn't require a particular barcode format.
Can probably use the same solution as for barcodes in https://github.com/sanger/General-Backlog-Items/issues/192
