### ISSUE TITLE
DPL-450 DPL-450 [EPIC?] As R&D we would like a new LIMS pipeline in order to support the tracking of BIOSCAN samples through a non-destructive extraction, 2-step PCR library prep, and pooling of 9216 samples for PacBio sequencing.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#201]
**User story**
DPL-450 [EPIC?] As R&D we would like a new LIMS pipeline in order to support the tracking of BIOSCAN samples through a non-destructive extraction, 2-step PCR library prep, and pooling of 9216 samples for PacBio sequencing.

I suspect this story is on the large side and if so we should consider ways of splitting it up.

**Who are the primary contacts for this story**
Scott T

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The LIMS can accept Faculty generated barcodes
- [ ] LIMS namespace requirements to be adhered to by Faculty.
- [ ] The pipeline should support pooling of 9216 samples. (TW ?I thought there was an option to treat this effectively as 1 sample?)
- [ ] Tag clash detection is required before pooling 24x 384-well plates together
- [ ] Ideally tag plates would not be defined by an upfront manifest, but decided at the tag PCR step.
- [ ] If this is implemented, the LIMS should suggest the next available tag plate (based on last used), but the user should be able to override this. This should be presented in a way to allow the user to check the suggestion and retrieve the corresponding plate from the freezer and return to the LIMS step later to perform the run.
- [ ] Positive and negative controls need to be supported. These controls will be introduced during the non-destructive extraction steps. Negative controls will be a designated empty well.
- [ ] The pipeline should have a mechanism (automated or manual) to import sample data from ToL Sample Tracking System, which will contain sample data
- [ ] As the library prep method is similar to Heron, it would be beneficial to use a similar LIMS approach (Limber)
- [ ] Pool data should be passed to Traction for sequencing

**Additional context**
**Assumptions:**
Index tags are combinatorial (96 forward primers x 96 reverse primers)
Index tags will be arrayed into 24x 384-well plates e.g. plate 1 contains 1-96F + 1-4R; plate 24 contains 1-96F + 93-96R
Pooling will initially be performed using a VBLOK (used in GBS pipeline), however 24x 384-well plates well be pooled together in this pipeline.
Some form of tracking will be required, this could be managed via SOP, but this adds significant risk.
Pooling will be performed on the Hamilton STAR for the final implementation (similar process to Heron and sc384 pooling)
Sample-level data will not be required to be passed to Traction as tag decoding will happen outside of Sanger (Guelph’s mBRAVE software)
Report from mBRAVE software will need to be downloaded and control wells analysed by QC team to monitor cross-contamination levels
Mechanism for download to be determined. Automated report download desired.
QC KPIs to be determined with Sanger Bioscan team from early sample data.
Controls will be added when new Non-Destructive Extraction automation is implemented.
NDE RFP is out to tender as of …
Initial sample set are unlikely to contain control samples until NDE instrument is implemented, but this is to be confirmed.
For the MVP sample manifests may need to be manually generated by SSR, but this is to be confirmed.
 
 
**Unknowns:**
The creation of forward and reverse primer plates may be outsourced to a 3rd party. This is R&D’s preference (R&D are currently setting up discussions with IDT)
If a 3rd party implements then Sanger may need to support foreign barcodes, although we may be able to specify barcode format.
If Sanger implements then we will need to track stock plates => single-use source plates => 24x384-well tag plates
Do we need tag set oligo sequences if Sanger is not doing the deplexing or is tag plate number + well coordinate enough.

**Comment by TWJW-SANGER** [comment]
Link to current [process map](https://drive.google.com/file/d/1j-W3sfzOGzcdt7OTtsl4dBGcDD-jQUbX/view?usp=sharing).

**Comment by TWJW-SANGER** [comment]
This story is intended as research.

I anticipate one or more of the team and myself meet up with Scott T to split the pipeline described above into a set of smaller individual stories, which ideally: 
- describe a Minimally Viable Product (MVP) to minimise effort while maximising value.
- can be individually delivered in about 2 weeks including testing.
- can be tested individually or in small sets (can we deliver the start and end of the pipeline and then fill in the middle?).

Acceptance Criteria:
- Output a set of refined user stories that deliver an MVP solution.
- Output a set of user stories for features outside of the MVP solution.

**Comment by andrewsparkes** [comment]
Starting a Lucidchart here:
https://lucid.app/lucidchart/b21a6020-df09-4be1-af69-26403ed467a1/edit?viewport_loc=1647%2C48%2C1511%2C835%2C0_0&invitationId=inv_44a43cc4-479b-4e19-924c-2a0182f4255c#
