### ISSUE TITLE
DPL-530 Check availability of data for LCMB-ISC timestamps

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/General-Backlog-Items#223]
**Description**
Take the timestamps identified during https://github.com/sanger/General-Backlog-Items/issues/209 and have a preliminary look at the data that is available for them, with the aim of identifying any problems early on. Write up any queries and findings in a place accessible to the project team, and to PSD.

**Who the primary contacts are for this work**
@KatyTaylor
Lee W
Sara V
Mark TL

**Tasks**
Getting basic data, including 'group by' criteria:
- [x] Extract set of relevant LCMB-ISC samples
- [x] Extract set of relevant LCMB-ISC submissions (clarify what is wanted for this one, as there are multiple submissions along the pipeline)
- [x] Extract set of relevant LCMB-ISC studies
- [x] Extract set of relevant LCMB-ISC projects
- [x] Extract set of relevant LCMB-ISC stock plates (might need clarity on what is meant by a 'stock plate')

(Present above all in one export if poss)

Getting timestamps:
- [x] 1
- [x] 2
- [x] 3
- [x] 3.1
- [x] 3.2
- [x] 4 (problem)
- [x] 5 (problem)
- [x] 6
- [x] 7 
- [x] 8 (problem)
- [x] 8.1
- [x] 9
- [x] 10
- [x] 11
- [x] 12
- [x] 13
- [x] 14
- [x] 15
- [x] 16
- [x] 17

Amalgamating data sources:
- [x] Get Tableau access
- [x] Verify can do joins between db tables

**Comment by KatyTaylor** [comment]
Have pushed up queries for all the timestamps to the linked pull request (in Event Warehouse repo as a temporary home). 

New column added to table on Miro board. https://miro.com/app/board/uXjVPX6xWqg=/?openActivity&utm_source=notification&utm_medium=email&utm_campaign=daily-updates&utm_content=view-activity

Outstanding questions for a few of the timestamps.

Summary is that I think we can currently get decent data for 17/20 of the timestamps, looking at the data since May this year. However, I wouldn't recommend using some of those data sources long term, as some won't be robust to future change.

**Comment by KatyTaylor** [comment]
Moving this to 'done' as I have checked the data for all the timestamps specified. Any further work for the LCMB-ISC timestamps can go into a new story.
