### ISSUE TITLE
DPL-797 Make STS tube label templates available to Squix printers

### ISSUE THREAD

**Issue by neilsycamore** [sanger/General-Backlog-Items#306]
As CASM Scientific Manager (Rob T) I would like to be able to print tube labels from STS via my squix printers, the template for which should be the same as those created in DPL-688

**Acceptance criteria**
To be considered successful the solution must allow:
be able to print 

**Additional context**
Requested via [RT781380](https://rt.sanger.ac.uk/Ticket/Display.html?id=781380)

From Sangeetha
Add the template “new_sts_barcode_template”  to /var/lib/sprint/label_templates to be accessed by Sprint for SQUIX printers

**Comment by harrietc52** [comment]
**Findings**

Printer here: http://squix424.internal.sanger.ac.uk/

**Questions**

- [ ] @Sangeetha-Bheeman where is label template with name `new_sts_barcode_template` stored?
- [ ] How to test this? How to access STS? Assume STS prints to SPrint via PMB??

**Todo**
(Assuming STS prints via PMB)
- [ ]  Add `new_sts_barcode_template` template to deployment project `roles/sprint/files/label_templates/new_sts_barcode_template.yml.erb`?
- [ ] Deploy `deploy_print_label_templates.yml` playbook

**Comment by Sangeetha-Bheeman** [comment]
`new_sts_barcode_template` - is the tube label template for CASM, it is created as a copy from `traction_tube_label_template` and stored in the PMB tables. 
[]([](https://print-my-barcode.psd.sanger.ac.uk/v1/label_templates/45)
)

![image](https://github.com/sanger/General-Backlog-Items/assets/93536758/1e1f6ddc-00bf-4a43-95e7-2c22fd294906)

[](https://print-my-barcode.psd.sanger.ac.uk/v1/label_templates/45
)

**Comment by harrietc52** [comment]
When sending POST to PMB (Testing #1 above), getting the below error. 

<img width="290" alt="Screenshot 2023-07-14 at 15 27 06" src="https://github.com/sanger/General-Backlog-Items/assets/11446617/d0b864cc-afb3-485d-acec-1ef1a77cb418">

**Comment by harrietc52** [comment]
Temp remove top/bottom label fields

```
      {
        "x": 26,
        "y": 18,
        "value": "<%= merge_fields[:round_label_top_line] %>",
        "font": 'proportional',
        "fontSize": 1.7,
        "rotation": 'east'
      },
      {
        "x": 24,
        "y": 21,
        "value": "<%= merge_fields[:round_label_bottom_line] %>",
        "font": 'proportional',
        "fontSize": 1.7,
        "rotation": 'east'
      }
```

**Comment by harrietc52** [comment]
{
   "print_job": {
      "printer_name":"squix424",
      "label_template_name":"new_sts_barcode_template",
      "labels":[
         {
            "barcode":"NT17617N",
            "first_line":"testing2",
            "second_line":"NT17617N",
            "third_line":"Standard sample",
            "fourth_line":"30-SEP-2022",
            "label_name":"main_label"
         }
      ],
      "copies":"1"
   }
}


<img width="326" alt="Screenshot 2023-07-17 at 10 40 55" src="https://github.com/sanger/General-Backlog-Items/assets/11446617/130f91ab-36be-4707-89a9-8f8fb4480996">

**Comment by harrietc52** [comment]
`rotation: north` (default)

<img width="379" alt="Screenshot 2023-07-17 at 11 01 01" src="https://github.com/sanger/General-Backlog-Items/assets/11446617/62737a48-128b-4576-8aae-a641a5fe19b4">

**Comment by harrietc52** [comment]
What Robert would prefer. I can change the x/y coordinates in the PMB SPrint config, but they will be different to the coordinates in the PMB database, with the same label template name?

<img width="344" alt="Screenshot 2023-07-17 at 11 19 45" src="https://github.com/sanger/General-Backlog-Items/assets/11446617/a2fe55ce-5386-4152-985d-c9b9bf901bc1">

**Comment by harrietc52** [comment]
```
[
  {
    "barcodeFields": [
      {
        "x": 2,
        "y": 22,
        "cellWidth": 0.4,
        "barcodeType": "datamatrix",
        "value": "<%= merge_fields[:barcode] %>"
      }
    ],
    "textFields": [
      {
        "x": 3,
        "y": 30,
        "value": "<%= merge_fields[:first_line] %>",
        "font": "proportional",
        "fontSize": 2.5
      },
      {
        "x": 3,
        "y": 33,
        "value": "<%= merge_fields[:second_line] %>",
        "font": "proportional",
        "fontSize": 2.5
      },
      {
        "x": 3,
        "y": 36,
        "value": "<%= merge_fields[:third_line] %>",
        "font": "proportional",
        "fontSize": 2.5
      }
    ]
  }
]
```

<img width="386" alt="Screenshot 2023-07-17 at 11 28 32" src="https://github.com/sanger/General-Backlog-Items/assets/11446617/518e1007-5f08-4f25-b6f1-6d224b013ba1">

**Comment by harrietc52** [comment]
```
[
  {
    "barcodeFields": [
      {
        "x": 4,
        "y": 23,
        "cellWidth": 0.4,
        "barcodeType": "datamatrix",
        "value": "<%= merge_fields[:barcode] %>"
      }
    ],
    "textFields": [
      {
        "x": 4,
        "y": 32,
        "value": "<%= merge_fields[:first_line] %>",
        "font": "proportional",
        "fontSize": 2.5
      },
      {
        "x": 4,
        "y": 35,
        "value": "<%= merge_fields[:second_line] %>",
        "font": "proportional",
        "fontSize": 2.5
      },
      {
        "x": 4,
        "y": 38,
        "value": "<%= merge_fields[:third_line] %>",
        "font": "proportional",
        "fontSize": 2.5
      }
    ]
  }
]
```

<img width="420" alt="Screenshot 2023-07-17 at 14 56 19" src="https://github.com/sanger/General-Backlog-Items/assets/11446617/f46143b1-d7b6-447a-88e3-3f41890d34f0">

**Comment by harrietc52** [comment]
- The template for the latest label above, is very different from the initial template `new_sts_barcode_template` which was created in https://github.com/sanger/General-Backlog-Items/issues/278 
- Why is this the case? Were they expected to be the same? Is it because the original was for Toshiba and this for Squix?
- Is the old template still needed? Why is the old template in the PMB database but not the deployment config?
- Does the new updated template need to be added to PMB DB?
- Is the new updated template okay to keep?
- Should the new updated template be renamed? 
- If the new updated is rename, what effects might that have? 
- e.g if STS is communicating with PMB, where does the template name get chosen/ decided? Do STS configure it, or does PMB decide. If so, how does PMB decide?
- Robert says the STS staging environment is not hooked up to the printers. But that he can see the printer list, including the new squix424, in the production view. How is it best to test the printing from STS if it isn't hooked up on UAT?

**Comment by harrietc52** [comment]
Rename `new_sts_barcode_template`  to `sts_tube_<size>_barcode_template` in both SPrint config and PMB DB

**Comment by harrietc52** [comment]
Example print request (like that from STS)
```
{
  "print_job": {
    "printer_name": "squix424",
    "label_template_name": "new_sts_barcode_template",
    "labels": [{
      "barcode": "NT17617N",
      "first_line": "first_line",
      "second_line": "second_line",
      "third_line": "third_line",
      "label_name": "main_label"
    }],
    "copies": "1"
  }
}
```

Final config for label template
```
[
  {
    "barcodeFields": [
      {
        "x": 4,
        "y": 23,
        "cellWidth": 0.4,
        "barcodeType": "datamatrix",
        "value": "<%= merge_fields[:barcode] %>"
      }
    ],
    "textFields": [
      {
        "x": 4,
        "y": 32,
        "value": "<%= merge_fields[:first_line] %>",
        "font": "proportional",
        "fontSize": 2.5
      },
      {
        "x": 4,
        "y": 35,
        "value": "<%= merge_fields[:second_line] %>",
        "font": "proportional",
        "fontSize": 2.5
      },
      {
        "x": 4,
        "y": 38,
        "value": "<%= merge_fields[:third_line] %>",
        "font": "proportional",
        "fontSize": 2.5
      }
    ]
  }
]

```
