### ISSUE TITLE
DPL-959 Create an example Sample Tracking report to identify common patterns and confirm report format

### ISSUE THREAD

**Issue by javidahmed64592** [sanger/General-Backlog-Items#349]
**User story**
Following the investigations in #342 and #345, we have identified the following columns to include in the Sample Tracking report:

- Study name
- Manifest ID (To be linkable to, or searchable within SequenceScape)
- Plate barcode
- First date, last date, and sample count of samples on a plate going through the QC assay of "Working Dilution - Plate Reader.*" (This provides assurance that work has commenced on a plate/sample)
- First date, last date, and sample count of samples going through library prep stage
- Library type
- Cost code(s) for sequencing runs (have to consider multiple sequencing runs and multiple samples on plate)
- Platform (i.e. NovaSeq X - NovaSeq 6000)

This has proved to be tricky to achieve in one SQL query and will likely need to be done in sets of queries/subqueries. The aim of this story is to generate a simple report with one event type and sequencing run stage for the samples. The data flow diagrams will need to be updated to reflect how the report is being created.

This can then be extended to include more event types and flowcell data to be more useful.  This will help plan the implementation of these queries to generate the report.

**Who are the primary contacts for this story**
TW KT AY

**Knowledge or Stake holders**
LH

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Report should include the following for submitted plates:
  - [x] Study name
  - [ ] Manifest ID
  - [x] Plate barcode
- [x] Join data from flowcell tables:
  - [x] First date, last date, and sample count for QC assay of "Working Dilution - Plate Reader.*"
  - [x] Library type and cost code for sequencing runs
  - [x] Platform
- [x] Join events data to these columns, first date, last date, and sample count for:
  - [x] `sample_manifest.updated`
  - [x] `labware.received`
  - [ ] `order_made`
  - [x] `library_start`
  - [x] `library_complete`
  - [x] `sequencing_start`
  - [x] `sequencing_complete`
- [x] Update data flow diagrams
  - _I've created a new diagram to combine the two data flow diagrams, see below_

References
This story has a non-blocking relationship with:
- #342
- #345

**Additional context**
The following two data flow diagrams were generated in #345:

1) [Sample Tracking Data Flow (events)](https://lucid.app/lucidchart/b7cc6467-1d04-4a79-81bf-5b732460cb23/edit?viewport_loc=416%2C699%2C2559%2C1236%2C0_0&invitationId=inv_045a4cd6-acda-4b6f-8f15-10503641e878)

2) [Sample Tracking Data Flow (flowcell)](https://lucid.app/lucidchart/994f9e42-18f6-4066-9ccb-9f79c2b9ac12/edit?viewport_loc=590%2C272%2C1937%2C936%2C0_0&invitationId=inv_4d077428-0601-4475-a2c2-d2759184d381)

I've created a new data flow diagram which combines these, showing how events can be joined to samples:

1) [Sample Tracking Data Flow](https://lucid.app/lucidchart/7c1883a9-d56f-4d49-a909-0652776862e1/edit?invitationId=inv_30cbc2de-d9cb-4d2f-9a1e-f4493eb940a3)

Here is the generated [Mock report](https://docs.google.com/spreadsheets/d/14T4fXw4gEWETFdk-tWag7mn05Q1T-460lfcJDs0R0uo/edit#gid=800383182).

Information about the report can be found in [Sample Tracking Report](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Sample+Tracking+Report).

This story is a part of the roadmap in [Sample Tracking Proof Of Concept](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Sample+Tracking+Proof+Of+Concept).

**Comment by javidahmed64592** [comment]
I have created a new sheet '[Mock report](https://docs.google.com/spreadsheets/d/14T4fXw4gEWETFdk-tWag7mn05Q1T-460lfcJDs0R0uo/edit#gid=800383182)'.

This sheet contains the structure of the sample tracking report, along with some results from a query I've written as a start to generating the report.

**Comment by javidahmed64592** [comment]
Putting this story on hold and moving it back to 'To do' as I am on leave next week, will move back to 'In progress' when I am back.

**Comment by KatyTaylor** [comment]
I've added post-its on your diagram - sorry if that's annoying and clutters it up - feel free to move them elsewhere! They're mostly about the joins and how rows will be duplicated - you've sort of solved this problem in the actual query by grouping by plate barcode and adding some aggregations, but the approach seems maybe a little messy to me...? Maybe fine for MVP. On the columns you're not aggregating, you're assuming the values will be the same for all rows. For example, I think this is not necessary valid for library type, because different wells on a stock plate could undergo different library preparations (although probably not the norm).

Think there's a typo in the query, should `COUNT(DISTINCT(sample_flowcell.sample_uuid)) working_dilution_count,` be `COUNT(DISTINCT(sample_flowcell.recorded_at)) working_dilution_count,`?

As you mentioned, I think it could be an issue not using LEFT JOINs, as you may lose rows if some events are missing for some samples.

Also added one comment on a cell in your spreadsheet, about the order_made event.

> You'll have to filter this further based on whatever else you've got attached to the event - because you'll have an order_made event for the library prep submission as well as the sequencing submission.

**Comment by javidahmed64592** [comment]
> Think there's a typo in the query, should `COUNT(DISTINCT(sample_flowcell.sample_uuid)) working_dilution_count,` be `COUNT(DISTINCT(sample_flowcell.recorded_at)) working_dilution_count,`?

If we use `sample_flowcell.recorded_at` then if two samples have the same timestamp, only one will be returned so I assume it would be better to use `sample_flowcell.sample_uuid` instead.

**Comment by javidahmed64592** [comment]
I refactored my query and managed to improve the performance so using `LEFT JOIN` no longer makes it timeout 🥳 I think it's important to use `LEFT JOIN` otherwise if a plate hasn't gone through a specific event, it should still be included in the report and using a regular `JOIN` would exclude it. The query now takes ~90s to run.

**Comment by javidahmed64592** [comment]
I've added a few more events from the [Tracking spreadsheet](https://docs.google.com/spreadsheets/d/1VmolGLvPp5KQoOW-95g2opb4e_CfgP5fth7vxkdQWcc/edit#gid=2142686892) and updated the [Mock report](https://docs.google.com/spreadsheets/d/14T4fXw4gEWETFdk-tWag7mn05Q1T-460lfcJDs0R0uo/edit#gid=800383182) to include these events. I still need to add these events to the Lucidchart diagram. This story specifies including one event type but it was easy enough to include the rest. I can update the story to mention all event types.

My query retrieves all flowcell runs for samples submitted under a specific study. I filter on `qc_result.assay = 'Working Dilution - Plate Reader v1.0'` and retrieve the earliest run to ensure work has commenced on samples. I checked all samples for a couple of different studies and found that the samples do have the same library type, cost code and platform. This may not always be the case as @KatyTaylor pointed out. I created a CTE block `sample_flowcell` with all of this data and group by  the sample UUIDs so that it returns one row per sample. I grouped these results by the plate barcode to get the sample count and data by plate.

I created another CTE block `sample_events` which makes use of the `flat_events_view` to get all desired sample events by filtering on `role_type = 'sample'`. I joined these events by the sample UUID. For manifest created and submitted, I selected the earliest date for these events. For the other events, I selected the earliest and latest dates.

I think this is good for an MVP and shows how we can join flowcell runs and events but we should answer these questions before planning next steps:

1) I was unable to find the manifest ID and in a Slack conversation, it was mentioned that this did not exist in the warehouse. Is there a way to retrieve this or should we proceed without it?

2) If there's an `order_made` event for both library prep submission and sequencing submission, how can I get the event linked to the sequencing submission? I can join this in the same way as the other events.

3) If library type is not necessarily always the same for all samples on a plate if they undergo different library preparations, how should we handle this? Any way to include all the different library types on one plate if I'm grouping by plate barcode?

4) Do any of the other columns in the query or CTE blocks need to be aggregated or adjusted?

**Comment by javidahmed64592** [comment]
I've updated [Sample Tracking Proof Of Concept](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Sample+Tracking+Proof+Of+Concept) to include this user story and the next one to generate intermediate datasets.

**Comment by KatyTaylor** [comment]
Hi @javidahmed64592 , I just took a look at your questions in case I could help. 

1. RE manifest id - Do you know what the reason is for wanting the manifest id? If it is to get aggregate data by manifest, we could use a proxy for it.. I think maybe it was suggested that we could use the manifest event timestamp? 

2. RE order_made events - Can you look into what other data you can see against the order_made events? 
    - What subjects do you see against them?
    - What metadata do you see against them?
 I think there should be something in there that will tell you whether it's a library prep or a sequencing submission.

3. RE library_type - I think it is an edge case where you'd have multiple library types on the same plate. However, I wonder if you could de-duplicate and concatenate them? Look at GROUP_CONCAT(). Not sure if it will affect the speed of the query.

4. RE other aggregations - not sure, you could consider using GROUP_CONCAT() for other columns if it works well for the above, in case you get multiple values.

**Comment by javidahmed64592** [comment]
Hi @KatyTaylor, thank you for your comment. I will create new tickets to investigate manifest ID, `order_made` and library type and move ahead with this one :)
