### ISSUE TITLE
DPL-984 Generate temporary/intermediate datasets for the sample tracking report

### ISSUE THREAD

**Issue by javidahmed64592** [sanger/General-Backlog-Items#350]
**User story**
In #349, a mock sample tracking report was generated using data from the `mlwarehouse` and `mlwh_events` databases. This report was created for only two studies so generating an intermediate dataset would help the performance of the query when including more stories. The query uses the `flat_events_view` view from the `mlwh_events` database, so one can be created for tables in `mlwarehouse` (`sample_flowcell` CTE block in the query).

**Who are the primary contacts for this story**
TW KT AY JA

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Create a new view `sample_flowcell_view` in the reporting database:
  - [x] `mlwhd_reporting` database in UAT
  - [x] `mlwh_reporting` database in production
- [x] Update sample tracking query to include this new view (see below)
- [x] Document this new view in Confluence

References
This story has a non-blocking relationship with:
- #349

**Additional context**
This view will be used in the view generated in #351.

Information about the report can be found in [Sample Tracking Report](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Sample+Tracking+Report).

This story is a part of the roadmap in [Sample Tracking Proof Of Concept](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Sample+Tracking+Proof+Of+Concept).

**Comment by javidahmed64592** [comment]
A potential solution for this story is to create a new view with the `mlwarehouse` tables, update the sample tracking query to use this new view and test the performance. This view can exist in the `mlwh_reporting` database.

Another solution is to use a program like `janitor` to track changes in flowcell runs for samples and create an intermediate table. That table can then be queried and joined with the events data to generate the report.

**Comment by javidahmed64592** [comment]
I have created this [Lucidchart diagram](https://lucid.app/lucidchart/a717713e-2d8a-4c8c-b0db-73070e53bbad/edit?invitationId=inv_f5103f57-2524-447f-afac-08b0fcb4bba8) outlining the view I have created in UAT. In production,

- `'mlwhd_mlwarehouse_proddata'.'sample_flowcell_view'` will be `'mlwh_reporting'.'sample_flowcell_view'`
- The rest of the `mlwhd_mlwarehouse` will be `mlwarehouse`

I tried to create this view in the `mlwhd_reporting` database in UAT but the admin and readwrite accounts don't appear to have access to this database, only the readonly account.

**Comment by javidahmed64592** [comment]
I have added `sample_flowcell_view` to `mlwhd_reporting` in UAT. The view uses a CTE block `study_names` to retrieve a list of studies that have been updated in the past X months. It then finds all samples and plates submitted under that study, and the dates that plates going through QC "Working Dilution - Plate Reader v1.0" is also included. This view assumes that for any given sample, most non-aggregated columns do not change but some columns need extra consideration as discussed in #349.

Currently, the report can be generated in ~30-40s when including the filter on study name `WHERE ... AND study_name = ... ` but this needs to be removed so the view can be generalised for all studies in the past X months. However, with current implementations of this view and the `sample_tracking_view`, the report does not generate before the query times out (300s), any suggestions on how I can optimise these queries to improve performance?

**Comment by javidahmed64592** [comment]
Brilliant suggestion @TWJW-SANGER, now instead of joining `sample_events` multiple times, I join it once and use conditionals and the report generates in ~30s when using studies from the past 6 months :)

**Comment by TWJW-SANGER** [comment]
@javidahmed64592 Excellent.

One last comment then. 

The first view, study_names, which JOINs the flowcell and sample table, I think assumes a one to one relationship between these tables.
However there is the possibility of samples being sequenced multiple times on different flowcells and in fact studies. 
i.e. the study linked on iseq_flow_cell might not be the study linked on the stock plate......

So I think we should explicitly comment in the code and documentation that we have this assumption and the report may not work as expected in these cases (multiple sequencing on different studies) for now.

Hopefully that makes sense.
