### ISSUE TITLE
Define a new message processor in ToL Lab Share to consume volume tracking messages

### ISSUE THREAD

**Issue by dasunpubudumal** [sanger/General-Backlog-Items#399]
**User story**
As a developer, I need to create a new message processor in ToL Lab Share to support volume tracking. For this story, I need to focus on the aliquot creation message. This message is produced by Traction and needs to be consumed by ToL Lab Share. After schema validation, it needs to be directed to MultiLIMS Warehouse RMQ for persistence.

The process diagram for the aliquot creation process is attached [here](https://lucid.app/lucidchart/6c8d5b09-4e57-4aba-a7ff-8d2cad161b3d/edit?viewport_loc=1354%2C-110%2C2000%2C1004%2CUIRBfRVooFlW&invitationId=inv_9886517c-b0aa-4670-9e87-d820b8ddbba7).

Please use the AMQP connections established in https://github.com/sanger/General-Backlog-Items/issues/398 to send the aliquot to MultiLIMS Warehouse RMQ.

**Who are the primary contacts for this story**
Dasun, Stuart, Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] To successfully consume messages coming from the topic exchange for aliquot creation.
- [ ] To successfully send the aliquot message to MultiLIMS Warehouse RMQ.
- [ ] To handle failures gracefully and log the failures properly. 

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
