### ISSUE TITLE
Y24-096: Publish volume tracking message from Traction Service

### ISSUE THREAD

**Issue by dasunpubudumal** [sanger/General-Backlog-Items#400]
**User story**
As a developer, I need to setup a connection between Traction Service and the Enterprise Message Queue (EMQ) so that I can publish volume tracking messages into EMQ which are then consumed by ToL Lab Share. 

I need to use the exchange and queues that are already set up in https://github.com/sanger/General-Backlog-Items/issues/397, and publish the aliquot creation message discussed in https://github.com/sanger/tol-lab-share/issues/57 to EMQ.

The schema for the message is defined in the story https://github.com/sanger/General-Backlog-Items/issues/396, and needs to be validated by fetching the schema from RedPanda schema store.

**Who are the primary contacts for this story**
Dasun, Stuart, Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] To establish a connection between Traction Service and EMQ to publish messages into the EMQ.
- [ ] To publish an aliquot creation message using Traction Service.
- [ ] To observe aliquot persisted in MultiLIMS Warehouse' `aliquot` table.

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/General-Backlog-Items/issues/396
- https://github.com/sanger/General-Backlog-Items/issues/397

References
This story has a non-blocking relationship with:
- https://github.com/sanger/tol-lab-share/issues/57

**Additional context**

Diagram: [Messaging for Volume Tracking](https://lucid.app/lucidchart/6c8d5b09-4e57-4aba-a7ff-8d2cad161b3d/edit?viewport_loc=1140%2C-72%2C2053%2C977%2CUIRBfRVooFlW&invitationId=inv_9886517c-b0aa-4670-9e87-d820b8ddbba7)
