### ISSUE TITLE
GPL-640 SAT Infrastructure pre work

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#41]
**Description**
GPL-640 | As LIMS, Systems & R&D teams we need to prepare UAT infrastructure to verify Beckman robotics (reworded)

_NB This backlog item is largely to visualize pre work required to set up the Biomeck / SAMI controller and DART database._

**Who the primary contacts are for this work**
Lesley S
Scott T
Tim C (Systems)
Rhona L (Procurement)

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Tasks**

- [x] Set up VMS UAT & PROD (Cherwell ticket 278128) 
- [x] Install DART UAT  & PROD database schema  (Cherwell ticket 278128) 
- [x] Commission UAT Biomek controller PC   (Cherwell ticket 278129) 

**Additional context or information**
New dedicated confluence page to collate information: https://ssg-confluence.internal.sanger.ac.uk/x/royeBg

**Comment by rl15** [comment]
PC is out for delivery Rhona, 22nd Sept

**Comment by rl15** [comment]
10am Project meeting 'Database have been installed' Tim C

**Comment by rl15** [comment]
So the next steps, in order, are:
 
Ensure that NetBios name resolution is working from the UAT machine (LMHosts file is setup).

Test this by pinging the server machine, using only the host name (NOT the FQDN or other DNS alias). For example, if my host machine is named “MIKESPC”, then pinging “MIKESPC” using a cmd ping command should work if NetBIOS is functioning properly.

Also it is worth being aware of the MS provided DTCPingtool.exe [support.microsoft.com] which is very useful for testing DTC comms.

Configure MSTDC on the UAT client pc using the same instructions [docs.microsoft.com] as for the Server, ensure that the “Distributed Transaction Coordinator” windows service is running on the UAT client.

Run the “Database Setup Utility” (search “database setup” in the start menu of the UAT machine), choose the “connect” option, then follow the prompts to connect to the DART Server. Whoever does this will require the DART username and the associated password provided to them by Kalyan/Aftab.

Assuming successful connection, run a simulated Biomek method virtually, to queue up data in the local database ready for synchronization.

Ensure that the “DART Sync Service” windows service is running and set to automatic startup on the UAT client machine.

Check the sync service logs on the UAT client machine, C:\Users\Public\Documents\DART\DARTSyncServiceLog.txt, look for errors. Also check if data for the simulated Biomek run is present in the central DART database. If it is not, you know it’s definitely not working. If you do see data show up, then it’s working.

**Comment by rl15** [comment]
Mike A (Beckman) wrote (ednesday, 7 October 2020 at 14:22)

DART is successfully installed on both Dev/Live SQL Server instances.
The MSDTC Service is running on both Dev/Live instances.
The MSDTC configuration according to the instructions here [docs.microsoft.com] are complete, awaiting the synchronization service connection from the clients.
An SQL Server Authenticated user with username “<redacted>” is set up on both Dev/Live instances: Note the passwords for both of these accounts are with DSA
