### ISSUE TITLE
As a team we would like a clear set of processes for bulk application shutdown, startup and disaster recovery.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#455]
**Description**
As a team we would like a clear set of processes for bulk application shutdown, startup and disaster recovery.

**Acceptance Criteria**
The following outputs from the research are produced:
- [ ] ...
This story should:
* Identify the use cases (some below) where the team need to bring down applications, prevent users using them and bring them back up again.
* Design a system that meets the use cases requirements.
* If required  - output user stories that implement this system, tidy existing tools/systems AND produce a documented process for each scenario.

We currently a number of disparate ways of bringing applications down, not all of which are clear in what they do.
Monit for example does not cover all of our applications and different applications seem to implement shutdown in different ways.

**Use Cases**
Use cases to consider.
* A new starter in PSD can shut down one or all applications in an environment cleanly and quickly with no data loss and w/o being spammed by error messages.
* A new starter in PSD can restart one or all applications in an environment cleanly and quickly.
* [Somewhat optional] Users can be directed to an informative error message that the service is unavailable.

**Additional context or information**
It may be worth considering any overlap with the deployment project

**Knowledge or Stake holders**
PSD

**Comment by harrietc52** [comment]
[Bring down (and up) Sequencescape, and dependent applications](https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Bring+down+%28and+up%29+Sequencescape%2C+and+dependent+applications)

**Comment by harrietc52** [comment]
# Tasks

- [ ] For any application with business logic, write a list of Application to applications dependencies 
- [ ] Create a Business Application Dependency Graph as a more visual representation of the above (with clear arrows)
- [ ] Research way that this graph could be build automatically, possibly via Ansible/ Graphviz etc etc
- [ ]  For each business application, write a list of its technical services it uses.   `ps -aux | grep service` / `systemctl ...` in the hosts command line / look at config in the deployment/ provision repo
- [ ] For each Business application and dependencies, clearly define what “clean shutdown” and “successful startup” means, including the order for shut down/ start up
- [ ] Once we have a clear idea of all the dependencies for each Business application, and their order, investigate the tool which might be most appropriate to implement this 

**Definitions**

Dependencies = both services and business application

Technical Services:
- RabbitMQ
- Monit
- Puma

Business Applications:
- Traction Service
- Traction UI
- Limber

**Comment by dasunpubudumal** [comment]
Application dependency graph (WIP): https://lucid.app/lucidchart/d3aa968f-1884-4182-b5a5-dbe2c1483461/edit?viewport_loc=-469%2C-102%2C2059%2C1127%2CMfypcG3VKEL6m&invitationId=inv_c4dadc51-ea05-4324-8ecf-41cb8328b500

**Comment by dasunpubudumal** [comment]
### On Dependencies

Cyclic dependencies between applications can hinder graceful application shutdowns and proper startups. Even though application shutdowns can be forced, application startups may not be possible in some cases.

**Sequencescape and Asset Audits** 

There is a direct cyclic dependency between Asset Audits and Sequencescape. The nature of this bi-directional dependency is as follows:
 - Sequencescape requires Asset Audits URL to display it within an iFrame.
 - Asset Audits require Sequencescape V2 API to make API calls.

It was decided that the directed dependency between Sequencescape and Asset Audits (i.e., meaning Sequencescape requiring Asset Audits to be up is not very strong. In other words, Sequencescape does not require Asset Audits to be up and running when Sequencescape spins its Puma servers up.

**Comment by harrietc52** [comment]
## 03/01/25

Harriet met with Katy, Abdullah, Andrew and Seena met in the 10am slot to share learnings so far and to discuss general direction for next steps. 

We discussed:
- the spreadsheet with each application and their dependencies is useful to start with but it would easily get out of date.  
- the order of applications when bringing up/ down. Having one whole list is more useful than a list for each application
- the commands to run shut down/ start up for each application. An improvement on the current situation already
- the Lucid Graph, a useful tool, but maybe it could be build automatically using a tool so not to get out of date
- Check Monit is reliably monitoring all applications. Sometimes an app shows a 500 but Monit status is OK
- Add usability notes for Monit to new Starter doc
- Add application level notes to new Starter doc

MVP 
- Create a new config file in the deployment project, showing each application and its dependencies
- A script, given an application, can say what what other applications it “is dependent on” directly
- A script, given an application, can say what what other applications it “is dependent on” directly and indirectly, in order of bringing down
- A script, given an application, can say what what other applications it “is a dependency of”
- Create Troubleshooting documentation, including possible error messages, and handy commands to access docker logs/ nginx logs/ system logs etc. Also include escalation routine. 
- Check the Health Status script is usable for quickly checking all is well in Production, returning the status and comment


Non-MVP
- Create a Graph ERD with these dependencies 
- Create a script to run the commands in the order, with checks, catches, given an application name, or multiple names, or all application
