### ISSUE TITLE
GPL-645-3 Clear machines not needed from Eta anymore

### ISSUE THREAD

**Issue by BenTopping** [sanger/General-Backlog-Items#56]
**Describe the bug**
Clean up work post migration of eta -> theta
Please see confluence notes [here]
(https://ssg-confluence.internal.sanger.ac.uk/display/PSD/How+to+migrate+FCE+environments)

**Tasks**
- [x] **Remove psd switch - 1 hour**
- Shut down instance after checking when not in use. 

- [x] **Snapshot of all eta machines - 1 day** 
- create script/ openstack command line. create snapshot, get image and upload to theta
- get snapshot of each machine in eta, UAT, TRAINING and PROD and psd-tools, and upload snapshot in theta. Preparation for destruction of eta machines.
- https://ssg-confluence.internal.sanger.ac.uk/display/OPENSTACK/Migrating+an+instance+from+one+OpenStack+platform+to+another

- [x] **Update architecture diagram - 2 hours** 
- Find diagram and show current state of prod hosts, Changes due to removal of switch etc
https://lucid.app/lucidchart/c64c2cdb-5f5e-4efe-b6c6-892314fbe9be/edit?shared=true&page=5IwzLyQPWeES#?folder_id=home&browser=icon

Primary contacts:
Harriet C, Eduardo M R, Ben T

**Comment by BenTopping** [comment]
Machines to snapshot:

- [x] pmb-prod
- [ ] saex-prod
- [ ] dsm-01-prod
- [ ] moni-prod
- [ ] smwf-prod
- [ ] sss1-prod
- [ ] sss0-prod
- [ ] limb-prod
- [ ] sslb-prod
- [ ] trac-prod
- [ ] labw-prod
- [ ] asau-prod
- [ ] gate-prod
- [ ] ware-prod
- [ ] plbc-prod
