### ISSUE TITLE
GPL-776 Deploy to prod

### ISSUE THREAD

**Issue by pjvv** [sanger/General-Backlog-Items#96]
## Tasks

- Create releases and deploy:
  - [SS](https://github.com/sanger/sequencescape): @emrojo 
    - [x] create release for prod
    - [x] deploy to training
    - [x] deploy to prod
  - [Limber](https://github.com/sanger/limber): @KatyTaylor 
    - [x] create release for prod
    - [x] deploy to training
    - [x] deploy to prod
  - [Samples extraction](https://github.com/sanger/samples_extraction): @JamesGlover - waiting for feedback for UAT
    - ~~[ ] create release for prod~~
    - ~~[ ] deploy to training~~
    - ~~[ ] deploy to prod~~
  - [Unified warehouse](https://github.com/sanger/unified_warehouse): @KatyTaylor 
    - [x] create release for prod
    - [x] deploy to prod
  - [Event warehouse](https://github.com/sanger/event_warehouse): @stevieing 
    - [x] create release for prod
    - [x] deploy to uat
    - [x] deploy to prod
  - [Lighthouse](https://github.com/sanger/lighthouse): @pjvv 
    - [x] create release for prod
    - [x] deploy to training
    - [x] deploy to prod
  - [Crawler](https://github.com/sanger/crawler): @pjvv 
    - [x] create release for prod
    - [x] deploy to training
    - [x] deploy to prod
  - [Lighthouse-ui](https://github.com/sanger/lighthouse-ui) [GPL-714-3](https://github.com/sanger/lighthouse-ui/issues/39): @harrietc52 
    - [x] create release for prod
    - [x] deploy to training
    - [x] deploy to prod
- [x] Modify lighthouse (endpoints): @emrojo 
- [x] Modify lighthouse-ui (hide new tab): @harrietc52 
- [x] Unified warehouse change: @KatyTaylor 
- Deployment (psd-deployment), push fixes to master as hotfixes: 
  - [x] Merge into master: @pjvv 
  - [x] Confirm DART config for production: @emrojo 
- [x] Create stories to verify 740 integrity: @Chris-Friend 
- Post deployment tasks:
  - [x] 771 needs to be modified for v1/v2: @alexperrin1 
  - [x] Update filtered positive rules to potentially NOT go to DART https://github.com/sanger/crawler/issues/163: @Chris-Friend 
  - [x] Update PAM queries https://github.com/sanger/General-Backlog-Items/issues/98: @Chris-Friend

**Comment by KatyTaylor** [comment]
Update on unified warehouse -
The key changes that are not maintenance updates in James's PR are in this commit - https://github.com/sanger/unified_warehouse/pull/133/commits/7a7a0eaf1790353c3109d3db98e655c2a858dcc6

It involves adding a new table to the MLWH called "samples extraction activity", and consumer code to populate it from messages. So that seems a safe change to deploy. I presume nothing will try to populate that table until the Samples Extraction changes are deployed.

Obviously can't guarantee that the maintenance changes won't cause any issues, although it seems to have been happily sitting in UAT for a while (since 3rd Nov).

The one thing I would question is whether James intended it to be UAT-ed by a customer - because if so, there could be further changes needed to it and we shouldn't release it yet.

**Comment by emrojo** [comment]
ok, yes, I think the same, is only creating a table, but is not in use until extraction is deployed, so it wont create problems to deploy unified warehouse without extraction

**Comment by harrietc52** [comment]
| x | x |
| a | a |

**Comment by emrojo** [comment]
Can we check this before deploying crawler?:

https://github.com/sanger/crawler/issues/177

**Comment by KatyTaylor** [comment]
Moving this to done as all the boxes are checked off, and doesn't make much sense for it to be in any intermediate column! The migration is not released but is tracked under different tickets
